services: 
    catalogdb:
      container_name: catalogdb
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=CatalogDb
      restart: always
      ports:
        - "5432:5432"
      volumes:
        - postgres_catalog:/var/lib/postgresql/data/
        
    basketdb: 
      container_name: basketdb
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=BasketDb
      restart: always
      ports:
        - "5433:5432"
      volumes:
        - postgres_basket:/var/lib/postgresql/data/
        
    distributedcache:
      container_name: distributedcache 
      restart: always
      ports:
        - "6379:6379" 
    
    catalog.api:
      container_name: catalog.api
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=8080
        - ASPNETCORE_HTTPS_PORTS=8081
        - ASPNETCORE_Kestrel__Certificates__Default__Password=sdklrcybgsczr
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/catalog.api.pfx
        - ConnectionStrings__Database=Server=catalogdb;Port=5432;Database=CatalogDb;User Id=postgres;Password=postgres;Include Error Detail=true
      volumes:
        - ~/.aspnet/https:/https:ro
      depends_on:
        - catalogdb
      ports:
        - "6000:8080"
        - "6060:8081"
        
    messagebroker:
      container_name: messagebroker
      hostname: ecommerce-mq
      environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
      restart: always
      ports:
        - "5672:5672"
        - "15672:15672"
    
    basket.api:
      container_name: basket.api
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=8080
        - ASPNETCORE_HTTPS_PORTS=8081
        - ASPNETCORE_Kestrel__Certificates__Default__Password=sdklrcybgsczr
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/basket.api.pfx
        - ConnectionStrings__Database=Server=basketdb;Port=5432;Database=BasketDb;User Id=postgres;Password=postgres;Include Error Detail=true
        - ConnectionStrings__Redis=distributedcache:6379
        - GrpcSettings__DiscountUrl=https://discount.grpc:8081
        - MessageBroker__Host=amqp://ecommerce-mq:5672
        - MessageBroker__Username=guest
        - MessageBroker__Password=guest
      volumes:
        - ~/.aspnet/https:/https:ro
      depends_on:
        - basketdb
        - distributedcache
        - discount.grpc
        - messagebroker
      ports:
        - "6001:8080"
        - "6061:8081"
        
    order.api:
      container_name: order.api
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=8080
        - ASPNETCORE_HTTPS_PORTS=8081
        - ASPNETCORE_Kestrel__Certificates__Default__Password=sdklrcybgsczr
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/order.api.pfx
        - ConnectionStrings__Database=Server=orderdb;Database=OrderDb;User Id=sa;Password=Rhonin1234;Encrypt=false;TrustServerCertificate=true
        - MessageBroker__Host=amqp://ecommerce-mq:5672
        - MessageBroker__Username=guest
        - MessageBroker__Password=guest
        - FeatureManagement__OrderFulfilment=true
      volumes:
        - ~/.aspnet/https:/https:ro
      depends_on:
        - orderdb
        - messagebroker
      ports:
        - "6003:8080"
        - "6063:8081"
    
    discount.grpc:
      container_name: discount.grpc
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=8080
        - ASPNETCORE_HTTPS_PORTS=8081
        - ConnectionStrings__Database=Data Source = discountdb
        - ASPNETCORE_Kestrel__Certificates__Default__Password=sdklrcybgsczr
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/discount.grpc.pfx
      volumes:
        - ~/.aspnet/https:/https:ro
      ports:
        - "6002:8080"
        - "6062:8081"
        
    yarpapigateway:
      container_name: yarpapigateway
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=8080
        - ASPNETCORE_HTTPS_PORTS=8081 
        - ASPNETCORE_Kestrel__Certificates__Default__Password=sdklrcybgsczr
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/apigateway.pfx
      volumes:
        - ~/.aspnet/https:/https:ro
        
      depends_on:
        - catalog.api
        - order.api
        - basket.api
      ports:
        - "6004:8080"
        - "6064:8081"
    
    orderdb:
      container_name: orderdb
      environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=Rhonin1234
      restart: always
      volumes:
        - mssql_order:/var/opt/mssql
      ports:
        - "1433:1433"
    
    web:
      container_name: web
      restart: always
      ports:
        - "3000:80"
      depends_on:
        - yarpapigateway